version: '3'

services:
  db:
    image: postgres:11.5
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
    ports:
      - "5432:5432"
  app:
    build: .
    links:
      - db
    depends_on:
      - db
    environment:
      - DB_URI=postgres://flask:flask@db/flask_test
